// 楽曲データの一括管理！「新しい曲を追加するときは、必ずファイルの『一番下（最後）』に書き足す」！
const musicData = [
    //sparkle！「新しい曲を追加するときは、必ずファイルの『一番下（最後）』に書き足す」！
    { name: "Nightless World", attr: "sparkle", time: 119 },
    { name: "Miracle Dream Traveler", attr: "sparkle", time: 120 },
    { name: "CHERRY HAPPY STREAM(ALBUM Mix)", attr: "sparkle", time: 121 },
    { name: "Grateful allegiance", attr: "sparkle", time: 124 },
    { name: "流星花火", attr: "sparkle", time: 124 },
    { name: "君印 Be Ambitious!!", attr: "sparkle", time: 126 },
    { name: "Kiss of Life", attr: "sparkle", time: 127 },
    { name: "フラジール", attr: "sparkle", time: 128 },
    { name: "FORBIDDEN RAIN", attr: "sparkle", time: 129 },
    { name: "野うさぎマーチ♪", attr: "sparkle", time: 130 },
    { name: "Temptation Magic", attr: "sparkle", time: 131 },
    { name: "歓迎☆トゥ・ウィンク雑技団", attr: "sparkle", time: 131 },
    { name: "アンリミテッド☆パワー!!!!!", attr: "sparkle", time: 131 },
    { name: "Dance in the Apocalypse", attr: "sparkle", time: 132 },
    { name: "聖少年遊戯", attr: "sparkle", time: 135 },
    { name: "RAINBOW CIRCUS", attr: "sparkle", time: 135 },
    { name: "ハナニナレ！", attr: "sparkle", time: 135 },
    { name: "メルティ♡キッチン", attr: "sparkle", time: 137 },
    { name: "祭夜絵巻", attr: "sparkle", time: 137 },
    { name: "We'll be ''Knights''", attr: "sparkle", time: 137 },
    { name: "プロローグのそのあとへ", attr: "sparkle", time: 137 },
    { name: "Knights the Phantom Thief", attr: "sparkle", time: 139 },
    { name: "=EYE=", attr: "sparkle", time: 141 },
    { name: "SWINGIN' PARONIRIA", attr: "sparkle", time: 142 },
    { name: "Eccentric Party Night!!", attr: "sparkle", time: 143 },
    { name: "PARANOIA STREET", attr: "sparkle", time: 144 },
    { name: "パラダイム・リバーシ！", attr: "sparkle", time: 144 },
    { name: "Trap For You", attr: "sparkle", time: 144 },
    { name: "凱旋歌", attr: "sparkle", time: 145 },
    { name: "僕のウィーク・ポイント", attr: "sparkle", time: 145 },
    { name: "エンドレスヴィーデ", attr: "sparkle", time: 146 },
    { name: "Neo Sanctuary", attr: "sparkle", time: 146 },
    { name: "The Tempest Night", attr: "sparkle", time: 147 },
    { name: "BREAKTHROUGH!", attr: "sparkle", time: 147 },
    { name: "ハレノヒSugar Wave", attr: "sparkle", time: 148 },
    { name: "PERFECTLY-IMPERFECT", attr: "sparkle", time: 149 },
    { name: "Swee2wink Love Letter", attr: "sparkle", time: 149 },
    { name: "熱血☆流星忍法帖", attr: "sparkle", time: 150 },
    { name: "Romancing Cruise", attr: "sparkle", time: 150 },
    { name: "Turbulent Storm", attr: "sparkle", time: 150 },
    { name: "Rebellion Star(ALBUM Mix)", attr: "sparkle", time: 152 },
    { name: "うさぎの森の音楽会", attr: "sparkle", time: 153 },
    { name: "Little Romance", attr: "sparkle", time: 155 },
    { name: "Magestic Magic", attr: "sparkle", time: 155 },
    { name: "FIST OF SOUL", attr: "sparkle", time: 155 },
    { name: "あんさんぶる体操!!", attr: "sparkle", time: 156 },
    { name: "指先のアリアドネ", attr: "sparkle", time: 156 },
    { name: "Heart aid Cafeteria", attr: "sparkle", time: 156 },
    { name: "ROCK ROAR", attr: "sparkle", time: 156 },
    { name: "It's (k)not lov?", attr: "sparkle", time: 156 },
    { name: "Dear World", attr: "sparkle", time: 156 },
    { name: "CELEBRATE!!", attr: "sparkle", time: 159 },
    { name: "炎纏焰踊千変万火", attr: "sparkle", time: 159 },
    { name: "Believe 4 leaves", attr: "sparkle", time: 160 },
    { name: "金色千夜夢舞台", attr: "sparkle", time: 160 },
    { name: "Crazy Anthem", attr: "sparkle", time: 161 },
    { name: "Romantic Xday!", attr: "sparkle", time: 161 },
    { name: "Chocola-Tic After School", attr: "sparkle", time: 161 },
    { name: "瞬きSign☆", attr: "sparkle", time: 161 },
    { name: "Be My Princess♡", attr: "sparkle", time: 161 },
    { name: "Heart Heat Beat", attr: "sparkle", time: 162 },
    { name: "勇侠青春謳", attr: "sparkle", time: 163 },
    { name: "UNDYING HOLY LOVE", attr: "sparkle", time: 163 },
    { name: "Ringing evil phone", attr: "sparkle", time: 164 },
    { name: "祝福のLibrary", attr: "sparkle", time: 166 },
    { name: "Psyche's Butterfly", attr: "sparkle", time: 166 },
    { name: "Melting Rouge Soul", attr: "sparkle", time: 167 },
    { name: "天翔KAGETSU", attr: "sparkle", time: 168 },
    { name: "SunnyTrip Summer", attr: "sparkle", time: 179 },
    
    //Brilliant！「新しい曲を追加するときは、必ずファイルの『一番下（最後）』に書き足す」！
    { name: "IMMORAL WORLD", attr: "Brilliant", time: 111 },
    { name: "オモイノカケラ", attr: "Brilliant", time: 113 },
    { name: "RISKY VENUS", attr: "Brilliant", time: 119 },
    { name: "Midnight Butlers", attr: "Brilliant", time: 120 },
    { name: "Darkness4", attr: "Brilliant", time: 120 },
    { name: "The Beast of the End", attr: "Brilliant", time: 121 },
    { name: "魅惑劇", attr: "Brilliant", time: 122 },
    { name: "LOCK YOUR GAZE", attr: "Brilliant", time: 123 },
    { name: "Silent Oath", attr: "Brilliant", time: 125 },
    { name: "Dream Collection", attr: "Brilliant", time: 125 },
    { name: "朧", attr: "Brilliant", time: 126 },
    { name: "Festive!", attr: "Brilliant", time: 128 },
    { name: "You're Speculation", attr: "Brilliant", time: 133 },
    { name: "夜空、然りとて鵲は", attr: "Brilliant", time: 133 },
    { name: "翼モラトリアム", attr: "Brilliant", time: 133 },
    { name: "剣戟の舞", attr: "Brilliant", time: 135 },
    { name: "楽園追放 -Faith Conquest-", attr: "Brilliant", time: 136 },
    { name: "百花繚乱、紅月夜", attr: "Brilliant", time: 138 },
    { name: "Rainbow Stairway", attr: "Brilliant", time: 139 },
    { name: "Savage Love Affair", attr: "Brilliant", time: 140 },
    { name: "ONLY YOUR STARS!(Trickstar Ver.)", attr: "Brilliant", time: 141 },
    { name: "HEART→BEATER!!!!(ALBAM Mix)", attr: "Brilliant", time: 141 },
    { name: "礼賛歌", attr: "Brilliant", time: 141 },
    { name: "Article of Faith", attr: "Brilliant", time: 141 },
    { name: "彗星HALATION", attr: "Brilliant", time: 142 },
    { name: "トゥウインクル空中戦", attr: "Brilliant", time: 142 },
    { name: "Graceful Punishment", attr: "Brilliant", time: 142 },
    { name: "Joyful×Box*", attr: "Brilliant", time: 143 },
    { name: "Holy Angel's Carol", attr: "Brilliant", time: 143 },
    { name: "エメラルドプラネット", attr: "Brilliant", time: 143 },
    { name: "辻風に吹かれて", attr: "Brilliant", time: 143 },
    { name: "Gate of the Abyss", attr: "Brilliant", time: 144 },
    { name: "WILDLAND SURVIVOR", attr: "Brilliant", time: 144 },
    { name: "Mischievous Paety Time!!", attr: "Brilliant", time: 145 },
    { name: "(RE) PLAY", attr: "Brilliant", time: 145 },
    { name: "Foolish Alien", attr: "Brilliant", time: 145 },
    { name: "No name yet", attr: "Brilliant", time: 146 },
    { name: "Death Game Holic", attr: "Brilliant", time: 146 },
    { name: "Daydream×Reality", attr: "Brilliant", time: 147 },
    { name: "セツナDrops", attr: "Brilliant", time: 147 },
    { name: "夢ノ咲流星隊歌", attr: "Brilliant", time: 147 },
    { name: "Honeycomb Summer", attr: "Brilliant", time: 149 },
    { name: "喪失寓意-LOST BALLADE-", attr: "Brilliant", time: 149 },
    { name: "百花繚乱、紅月夜 2025ver.", attr: "Brilliant", time: 149 },
    { name: "ハートプリズム・シンメトリー", attr: "Brilliant", time: 151 },
    { name: "ポケットに宇宙", attr: "Brilliant", time: 151 },
    { name: "Never-ending Stage!!!!", attr: "Brilliant", time: 151 },
    { name: "Aisle, be with you", attr: "Brilliant", time: 153 },
    { name: "Fight Is Only Fate", attr: "Brilliant", time: 153 },
    { name: "青春Emergency", attr: "Brilliant", time: 154 },
    { name: "U.S.A.", attr: "Brilliant", time: 154 },
    { name: "Luminous Crown", attr: "Brilliant", time: 155 },
    { name: "Secret Masquarade", attr: "Brilliant", time: 156 },
    { name: "JUMPIN' LUCK BEAT", attr: "Brilliant", time: 157 },
    { name: "Brilliant Smile", attr: "Brilliant", time: 158 },
    { name: "Bye-Bye Buddy", attr: "Brilliant", time: 158 },
    { name: "Ruby Love", attr: "Brilliant", time: 161 },
    { name: "ハニートラップ・マリアージュ", attr: "Brilliant", time: 162 },
    { name: "麗しのナイチンゲール", attr: "Brilliant", time: 163 },
    { name: "Feathers of Ark", attr: "Brilliant", time: 164 },
    { name: "RELAX PARADISE", attr: "Brilliant", time: 164 },
    { name: "Absolute Perfection", attr: "Brilliant", time: 164 },
    { name: "あんさんぶるトレーニング", attr: "Brilliant", time: 165 },
    { name: "ハロウィン・ランデブー", attr: "Brilliant", time: 166 },
    { name: "Across the universe", attr: "Brilliant", time: 166 },
    { name: "Twilight Pentagram", attr: "Brilliant", time: 167 },
    { name: "Heart Collector", attr: "Brilliant", time: 168 },
    { name: "Angelic Grace", attr: "Brilliant", time: 169 },
    { name: "Or the Beautiful Golden Drop", attr: "Brilliant", time: 170 },
    { name: "ヒカリスペクトル", attr: "Brilliant", time: 170 },
    { name: "RaRaRa*Station!", attr: "Brilliant", time: 170 },
    { name: "NEW DAYBREAK", attr: "Brilliant", time: 176 },

    //Glitter！「新しい曲を追加するときは、必ずファイルの『一番下（最後）』に書き足す」！
    { name: "紅月いろは唄", attr: "Glitter", time: 123 },
    { name: "Sweet Sweet White Song", attr: "Glitter", time: 124 },
    { name: "Blooming World", attr: "Glitter", time: 125 },
    { name: "GROWING STARRYDAYS", attr: "Glitter", time: 126 },
    { name: "ベリイ・ベリイ・スイート・ホワイト♡", attr: "Glitter", time: 127 },
    { name: "Mémoire Antique", attr: "Glitter", time: 129 },
    { name: "Eternal Weaving", attr: "Glitter", time: 129 },
    { name: "Be The Party Bee!", attr: "Glitter", time: 130 },
    { name: "ムーンライトディスコ", attr: "Glitter", time: 130 },
    { name: "Welcome to the Trickstar Night☆", attr: "Glitter", time: 132 },
    { name: "INfinite Star", attr: "Glitter", time: 134 },
    { name: "ハム太郎とっとこうた", attr: "Glitter", time: 134 },
    { name: "DESTRUCTION ROAD", attr: "Glitter", time: 136 },
    { name: "LEMON SQASH CHEERS!", attr: "Glitter", time: 136 },
    { name: "Ruler's Truth", attr: "Glitter", time: 136 },
    { name: "Play''Tag''", attr: "Glitter", time: 137 },
    { name: "Crush of Judgement", attr: "Glitter", time: 138 },
    { name: "KING", attr: "Glitter", time: 138 },
    { name: "SUPER NOVA REVOLU5TAR", attr: "Glitter", time: 136 },
    { name: "恋はプリマヴェーラ！", attr: "Glitter", time: 140 },
    { name: "POLYPOHONIC WORLD", attr: "Glitter", time: 140 },
    { name: "Distorted Heart", attr: "Glitter", time: 141 },
    { name: "セイクリッド ルイン", attr: "Glitter", time: 141 },
    { name: "Awakeing Myth", attr: "Glitter", time: 142 },
    { name: "I ''Witch'' You A Happy Halloween!", attr: "Glitter", time: 143 },
    { name: "Valentine Eve's Nightmare", attr: "Glitter", time: 144 },
    { name: "羽ばたきのフォルティシモ", attr: "Glitter", time: 144 },
    { name: "Milky Starry Charm", attr: "Glitter", time: 144 },
    { name: "メイド・イン・トキメキ♪", attr: "Glitter", time: 144 },
    { name: "デートプランA to Z", attr: "Glitter", time: 145 },
    { name: "シュガー・スパイス方程式", attr: "Glitter", time: 145 },
    { name: "LOUDEST BUGS", attr: "Glitter", time: 145 },
    { name: "斬ー決意ノ刃ー", attr: "Glitter", time: 146 },
    { name: "夜に駆ける", attr: "Glitter", time: 146 },
    { name: "Ai☆$!!", attr: "Glitter", time: 146 },
    { name: "虹色のSeasons", attr: "Glitter", time: 146 },
    { name: "メランコリーを駆け抜けろ♥", attr: "Glitter", time: 147 },
    { name: "THE GENESIS", attr: "Glitter", time: 149 },
    { name: "Black Out See Saw", attr: "Glitter", time: 149 },
    { name: "Voice of Sword", attr: "Glitter", time: 150 },
    { name: "Magic for your ''Switch''", attr: "Glitter", time: 150 },
    { name: "OVERFLOW LIGHT UP!!!!!", attr: "Glitter", time: 151 },
    { name: "催花雨の片道切符", attr: "Glitter", time: 152 },
    { name: "夏鳥の詩 ーサマーバードー", attr: "Glitter", time: 154 },
    { name: "Finder Girl", attr: "Glitter", time: 154 },
    { name: "円環のRefraction", attr: "Glitter", time: 155 },
    { name: "Artistic Partisan", attr: "Glitter", time: 155 },
    { name: "Light on the Orbit", attr: "Glitter", time: 155 },
    { name: "Noir Neige", attr: "Glitter", time: 156 },
    { name: "スキスキハンター♡", attr: "Glitter", time: 156 },
    { name: "Switching Journy", attr: "Glitter", time: 156 },
    { name: "パラレルメイズ", attr: "Glitter", time: 157 },
    { name: "幸せの歌", attr: "Glitter", time: 157 },
    { name: "月光奇譚", attr: "Glitter", time: 158 },
    { name: "NA NA NA SUMMER NIGHT BeeAT", attr: "Glitter", time: 158 },
    { name: "僕らのステラ", attr: "Glitter", time: 158 },
    { name: "ネビュラ", attr: "Glitter", time: 161 },
    { name: "Resurrection of Soul", attr: "Glitter", time: 161 },
    { name: "Promise of Swords", attr: "Glitter", time: 162 },
    { name: "Sustain Memories", attr: "Glitter", time: 162 },
    { name: "Ghostic Treat House", attr: "Glitter", time: 162 },
    { name: "Eccentric Party Night!! 追憶セレクションMix", attr: "Glitter", time: 162 },
    { name: "Seven Days ''Prismagic''", attr: "Glitter", time: 162 },
    { name: "Fairy Tale Library", attr: "Glitter", time: 162 },
    { name: "ワチャガナドゥ？", attr: "Glitter", time: 162 },
    { name: "HELLO, NEW YEAR!", attr: "Glitter", time: 163 },
    { name: "Coruscate Breeze", attr: "Glitter", time: 164 },
    { name: "Dawning Angels", attr: "Glitter", time: 164 },
    { name: "Castle of my Heart", attr: "Glitter", time: 165 },
    { name: "幸福論", attr: "Glitter", time: 165 },
    { name: "迷宮電子回廊", attr: "Glitter", time: 167 },
    { name: "KEEP OUT", attr: "Glitter", time: 171 },

    //Flash！「新しい曲を追加するときは、必ずファイルの『一番下（最後）』に書き足す」！
    { name: "Living on the edge", attr: "Flash", time: 125 },
    { name: "Genuine Revalation", attr: "Flash", time: 127 },
    { name: "Galaxy Destiny", attr: "Flash", time: 128 },
    { name: "Knockin' Fantasy", attr: "Flash", time: 129 },
    { name: "Stippling", attr: "Flash", time: 129 },
    { name: "Last Lament", attr: "Flash", time: 131 },
    { name: "1st SING-ALONG☆", attr: "Flash", time: 134 },
    { name: "Mystic Fragrance", attr: "Flash", time: 135 },
    { name: "来来☆2winkイリュージョン", attr: "Flash", time: 136 },
    { name: "今宵月の館にて", attr: "Flash", time: 137 },
    { name: "Sunlit Smile!", attr: "Flash", time: 138 },
    { name: "Have you been naughty or nice?", attr: "Flash", time: 138 },
    { name: "Twin Wedding Vows", attr: "Flash", time: 138 },
    { name: "Wanderlust Sailing", attr: "Flash", time: 139 },
    { name: "コトノハカンタービレ", attr: "Flash", time: 139 },
    { name: "フュージョン", attr: "Flash", time: 141 },
    { name: "Love Ra*bits Party!!", attr: "Flash", time: 142 },
    { name: "Deep into you", attr: "Flash", time: 142 },
    { name: "B100d Hunter", attr: "Flash", time: 143 },
    { name: "2wink Star Beat☆", attr: "Flash", time: 144 },
    { name: "薄紅色の約束", attr: "Flash", time: 145 },
    { name: "BIGBANG REFLECTION!!", attr: "Flash", time: 145 },
    { name: "Fighting Dreamer", attr: "Flash", time: 145 },
    { name: "始まりのファンタジア", attr: "Flash", time: 145 },
    { name: "Fight for Judge", attr: "Flash", time: 146 },
    { name: "愉快痛快 That's alright!", attr: "Flash", time: 146 },
    { name: "Helter-Spider", attr: "Flash", time: 146 },
    { name: "スターライトパレード", attr: "Flash", time: 147 },
    { name: "イースター・カーニバル", attr: "Flash", time: 147 },
    { name: "堕天使たちの晩餐会", attr: "Flash", time: 147 },
    { name: "Noisy : Beep", attr: "Flash", time: 148 },
    { name: "天下無敵☆メテオレンジャー！", attr: "Flash", time: 149 },
    { name: "月下無双、紅の舞", attr: "Flash", time: 149 },
    { name: "Love×me⇄monsteR", attr: "Flash", time: 149 },
    { name: "EXCEED", attr: "Flash", time: 150 },
    { name: "Hysteric Humanoid", attr: "Flash", time: 150 },
    { name: "Crazy Roulette", attr: "Flash", time: 151 },
    { name: "Melody in the Dark", attr: "Flash", time: 151 },
    { name: "TRICK with TREAT!! with UNDED", attr: "Flash", time: 151 },
    { name: "メテオスクランブル☆流星隊！", attr: "Flash", time: 151 },
    { name: "UTAKATA DANCE FLOOR", attr: "Flash", time: 151 },
    { name: "クマクマレスQ!", attr: "Flash", time: 152 },
    { name: "Musica Vita! -ムジカ・ヴィータ-", attr: "Flash", time: 152 },
    { name: "BUBBLE GEM DANCE", attr: "Flash", time: 152 },
    { name: "終わらないシンフォニア", attr: "Flash", time: 153 },
    { name: "ハニーミルクはお好みで", attr: "Flash", time: 153 },
    { name: "Color Arise", attr: "Flash", time: 154 },
    { name: "それは残像の消失点", attr: "Flash", time: 154 },
    { name: "FALLIN' LOVE=IT'S WONDERLAND", attr: "Flash", time: 155 },
    { name: "Acanthe", attr: "Flash", time: 155 },
    { name: "Crossing×Heart", attr: "Flash", time: 156 },
    { name: "君恋志願", attr: "Flash", time: 156 },
    { name: "Love it Love it", attr: "Flash", time: 157 },
    { name: "Le temps des fleurs", attr: "Flash", time: 157 },
    { name: "Unstoppable Love!", attr: "Flash", time: 157 },
    { name: "大いなる愛の前に全ては巡り来る", attr: "Flash", time: 157 },
    { name: "Tell Your World", attr: "Flash", time: 159 },
    { name: "ハンズクラフト", attr: "Flash", time: 159 },
    { name: "Dreaming Ocean", attr: "Flash", time: 160 },
    { name: "A little bit UP!!", attr: "Flash", time: 160 },
    { name: "Deep Eclipse", attr: "Flash", time: 161 },
    { name: "らびゅ＆ピース伝説", attr: "Flash", time: 163 },
    { name: "Wonderful Happiness", attr: "Flash", time: 164 },
    { name: "星の鳴動響きし時に", attr: "Flash", time: 165 },
    { name: "Wish upon a MUSIC!!", attr: "Flash", time: 165 },
    { name: "絲", attr: "Flash", time: 166 },
    { name: "VERMILION", attr: "Flash", time: 168 },
    { name: "罪の底", attr: "Flash", time: 169 },
    { name: "しょーがいゼッタイそーあい宣言♥", attr: "Flash", time: 170 },
    { name: "SAKE OF LOVE", attr: "Flash", time: 186 },
    
    //All！「新しい曲を追加するときは、必ずファイルの『一番下（最後）』に書き足す」！
    { name: "Walk with your smile", attr: "All", time: 115 },
    { name: "BRAND NEW STARS!!", attr: "All", time: 122 },
    { name: "BUKUBU NEW STARS!!", attr: "All", time: 125 },
    { name: "BRIGHTEST STARS!!", attr: "All", time: 141 },
    { name: "Surprising Thanks!!", attr: "All", time: 142 },
    { name: "両片思いの交差点で、君にまた逢いたくて", attr: "All", time: 144 },
    { name: "BRIGHTEST STARS!!(Mainstream Megasphere ver.)", attr: "All", time: 145 },
    { name: "ONLY YOUR STARS!(10th Anniversary Mix)", attr: "All", time: 146 },
    { name: "キセキ", attr: "All", time: 149 },
    { name: "Star's Ensemble!", attr: "All", time: 153 },
    { name: "We Are Light", attr: "All", time: 155 },
    { name: "FUSIONIC STARS!!", attr: "All", time: 160 },
    { name: "Life is so Doramatic!!", attr: "All", time: 161 },
    { name: "One with One", attr: "All", time: 165 },
    { name: "LIMIT BREAK DREAMERS", attr: "All", time: 168 },
    { name: "RISE STAR'S SPIRITS", attr: "All", time: 170 },
    { name: "Walk with your smile Acoustic Ver.", attr: "All", time: 178 },
    { name: "年越しあんさんぶる！！2020→2021", attr: "All", time: 194 },
    { name: "年越しあんさんぶる！！2021→2022", attr: "All", time: 199 },
    { name: "年越しあんさんぶる！！2022→2023", attr: "All", time: 214 },
    

    // 以上2026.4.30時点、以下今後の拡張用　！「新しい曲を追加するときは、必ずファイルの『一番下（最後）』に書き足す」！ sparkle Brilliant Glitter Flash All　今後の拡張用
    { name: "CALL YOUR NAME!!", attr: "All", time: 162 },
    { name: "CIVIL WAR", attr: "Flash", time: 154 },
    { name: "RED GARDEN", attr: "glitter", time: 169 },
    { name: "最新", attr: "glitter", time: 120 },










];
 
